// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: proto/gpu.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GPUService_AllocateGPU_FullMethodName = "/gpu.GPUService/AllocateGPU"
)

// GPUServiceClient is the client API for GPUService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GPUServiceClient interface {
	AllocateGPU(ctx context.Context, in *AllocateRequest, opts ...grpc.CallOption) (*AllocateResponse, error)
}

type gPUServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGPUServiceClient(cc grpc.ClientConnInterface) GPUServiceClient {
	return &gPUServiceClient{cc}
}

func (c *gPUServiceClient) AllocateGPU(ctx context.Context, in *AllocateRequest, opts ...grpc.CallOption) (*AllocateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AllocateResponse)
	err := c.cc.Invoke(ctx, GPUService_AllocateGPU_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GPUServiceServer is the server API for GPUService service.
// All implementations must embed UnimplementedGPUServiceServer
// for forward compatibility.
type GPUServiceServer interface {
	AllocateGPU(context.Context, *AllocateRequest) (*AllocateResponse, error)
	mustEmbedUnimplementedGPUServiceServer()
}

// UnimplementedGPUServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGPUServiceServer struct{}

func (UnimplementedGPUServiceServer) AllocateGPU(context.Context, *AllocateRequest) (*AllocateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AllocateGPU not implemented")
}
func (UnimplementedGPUServiceServer) mustEmbedUnimplementedGPUServiceServer() {}
func (UnimplementedGPUServiceServer) testEmbeddedByValue()                    {}

// UnsafeGPUServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GPUServiceServer will
// result in compilation errors.
type UnsafeGPUServiceServer interface {
	mustEmbedUnimplementedGPUServiceServer()
}

func RegisterGPUServiceServer(s grpc.ServiceRegistrar, srv GPUServiceServer) {
	// If the following call pancis, it indicates UnimplementedGPUServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GPUService_ServiceDesc, srv)
}

func _GPUService_AllocateGPU_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AllocateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GPUServiceServer).AllocateGPU(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GPUService_AllocateGPU_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GPUServiceServer).AllocateGPU(ctx, req.(*AllocateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GPUService_ServiceDesc is the grpc.ServiceDesc for GPUService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GPUService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gpu.GPUService",
	HandlerType: (*GPUServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AllocateGPU",
			Handler:    _GPUService_AllocateGPU_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/gpu.proto",
}
